// Source: https://www.nerdfonts.com/cheat-sheet
exports.icons = {
  archive: "\uF1C6",
  audio: "\uF1C7",
  binary: "\uF471",
  book: "\uF02D",
  code: "\uF121",
  drawing: "\uF6DD",
  excel: "\uF1C3",
  folder: "\uF115",
  font: "\uFBD4",
  file: "\uF016",
  image: "\uF1C5",
  text: "\uF0F6",
  powerpoint: "\uF1C4",
  video: "\uF1C8",
  word: "\uF1C2",

  folders: {
    documents: "\uF719",
    downloads: "\uF74C",
    dropbox: "\uF6E2",
    games: "\uF795",
    git: "\uE702",
    googledrive: "\uE731",
    music: "\uF001",
    nodemodules: "\uF898",
    pictures: "\uF74E",
    savedgames: "\uF795",
    users: "\uF74B",
    videos: "\uF880"
  },
  
	unique: {
    ai: "\uE7B4",    
    c: "\uFB70",    
    cs: "\uF81A",
    css: "\uE614",
    cpp: "\uFB71", 
    html: "\uE736",
    java: "\uE738",
    js: "\uE74E",
    json: "\uE60B",
    jsx: '\uE7bA',
    md: "\uE73E",
    pdf: "\uF411",
    psd: "\uE7B8",
    py: "\uF81F",
    sass: "\uE74b",
    scss: "\uE74b",
    ts: "\uE628",
  }
}

exports.fileTypes = {
  audio: ['flac', 'mp3', 'wav', 'wma'],
  archive: ['7z', 'rar', 'zip'],
  binary: ['bak', 'bin', 'exe', 'iso', 'msi'],
  book: ['epub', 'mobi', 'azw', 'azw3'],
  code: ['bat', 'h', 'xml', 'map', 'xps'],
  drawing: ['vsdx', 'vsd', 'xcf'],
  excel: ['xlsx', 'xlsm', 'xlsb', 'xltm', 'xls', 'xlam'],
  font: ['otf', 'ttf', 'woff', 'fnt'],
  image: ['bmp', 'gif', 'ico', 'jpg', 'jpeg', 'png', 'raw', 'svg', 'tiff'],
  powerpoint: ['potm', 'potx', 'ppam', 'ppsm', 'ppsx', 'pptx'],
  text: ['csv', 'db', 'dll', 'ini', 'log', 'odt', 'rtf', 'sav', 'txt',],
  video: ['3gp', 'avi', 'flv', 'mkv', 'mov', 'mp4', 'mpg', 'mpeg', 'wmv'],
  word: ['doc', 'docx', 'docm', 'dotm', 'dotx'],
  unique: ['ai','c', 'cs', 'css', 'cpp', 'html', 'java', 'json', 'js', 'jsx', 'md', 'pdf', 'psd', 'py', 'ts', 'sass', 'scss']
}